<?php
$id=$_GET["id"];
include_once("../connection.php");
if($conn->connect_error){
        echo"failed<br>";
    }
    else{
        echo"successful<br>";
    }
    $id=$_GET['id'];
    $cmd="delete from review where r_id=$id";
    $data=mysqli_query($conn,$cmd);
    if($data){
        header('location:review.php');
}
else{
    echo"<br>failed";
}
 ?>